<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="tom-laptop" name="com.skalicky.tomas.cv.businesslogic.CVServiceImplIntegrationalTest" tests="1" failures="1" timestamp="19 Apr 2014 18:20:13 GMT" time="0.015" errors="0">
  <testcase name="testGetCV" time="0.015" classname="com.skalicky.tomas.cv.businesslogic.CVServiceImplIntegrationalTest">
    <failure type="java.lang.RuntimeException" message="java.io.FileNotFoundException: class path resource [data/tomas-skalicky-cv-en.json] cannot be opened because it does not exist">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: class path resource [data/tomas-skalicky-cv-en.json] cannot be opened because it does not exist
	at com.skalicky.tomas.cv.businesslogic.CVServiceImpl.getCV(CVServiceImpl.java:43)
	at com.skalicky.tomas.cv.businesslogic.CVServiceImplIntegrationalTest.testGetCV(CVServiceImplIntegrationalTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.io.FileNotFoundException: class path resource [data/tomas-skalicky-cv-en.json] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:158)
	at com.skalicky.tomas.cv.businesslogic.CVServiceImpl.getCVResource(CVServiceImpl.java:51)
	at com.skalicky.tomas.cv.businesslogic.CVServiceImpl.getCV(CVServiceImpl.java:38)
	... 32 more
]]>
    </failure>
  </testcase> <!-- testGetCV -->
</testsuite> <!-- com.skalicky.tomas.cv.businesslogic.CVServiceImplIntegrationalTest -->
